version: "3.6"

services:
  vmtree-adapter:
    container_name: vmtree-adapter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    restart: always
    ports:
      - 8080:8080
    command: start-dev

networks:
  default:
    external:
      name: chainlink-node_default
